language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-9
            - g++-9

stages:
  - build and test
  - deploy binaries

# Deploy Teplates
template_deploy : &template_deploy
  script:
    - mkdir travispackaging && cd travispackaging && cmake ..
    - cmake --build . --target PACKAGE
    - cd ..
  deploy:
    provider: releases
    api_key:
      secure: NA3i42LJkvMqmp7g0jdAnJNrsDdh7jJUHlHT+kGYeZF6kLRYHHIOldv4bM4hM2HcLUo/S6ngKZ2newjTAqrVRlZ2PWtkriZ3CoVTqyYyE0a0n21hEKX0wkVDWdheh1Q3LWtgBNmhFGwJUZiyJ2VzDIMefljHiT+nyAKWPTdjO/bYIzmCqI7OOplcuKWXok2FbJ163bLb03V9oCxazrPjeQqNf/TQBmPgqq9r8E5IetmIgukSvn2+lm/usNk9KXUCRWGWUd0t+KcdifvIvnpOqQj32mYKaa0T5u9AWKSPUFC1sS0Pcg+e8yPoKjG0JPybl4g43+owpwEiCaEOg/N8WXWcMOTYHcomRFurv18yRlMkXOz3Ul/DA7jG4PHTPJd6TPADSOkw9OpL0bYS+qjbGpLVsE5x2/KaYb5xDBMwdWJa9WEbxaNo2CtnPJrII7F2qZNy2L4jwwDH7t6DKNwrKwr+YFf2TMYxziR8+lTC3DoNskU00MLm/s45SHzze2Zog60SZbiT9ZaCDdFPYbOcQ1vGWYUkoYJM70v6s82nl3UycTMZ69XdrChtNnj4Kvs7Hx4+B9uSjK24+JLBO8I/qlwXcDh1xo+svbZV+haAT4M/WqETipdjanzn6fND5wykndr2a1gNWdXYJdnic2H1dEUy9LtiuANsubJtF8YzFXI=
    file_glob: true
    file: packages/*
    draft: true
    cleanup: false
    on:
      repo: xNWP/xTGA
      tags: true

jobs:
  include:
      # Linux 64-bit
    - stage: build and test
      name: Linux 64-bit
      os: linux
      install: &install_linux
        - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc
        - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-9 /usr/bin/g++
        - wget https://github.com/Kitware/CMake/releases/download/v3.15.0-rc3/cmake-3.15.0-rc3-Linux-x86_64.tar.gz
        - tar -xf cmake-3.15.0-rc3-Linux-x86_64.tar.gz
        - sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.15.0-rc3-Linux-x86_64/bin/cmake /home/travis/bin/cmake
        - sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.15.0-rc3-Linux-x86_64/bin/ctest /home/travis/bin/ctest
      env: &linux-64-toolchain
        - TOOLCHAIN=""
      script: &script_linux
        - mkdir build && cd build
        - cmake ${TOOLCHAIN} ..
        - make all
        - ctest --verbose

      # Linux 32-bit
    - stage: build and test
      name: Linux 32-bit
      os: linux
      install: *install_linux
      before_script: &before-script-linux32
        - sudo apt-get install -y gcc-9-multilib
        - sudo apt-get install -y g++-9-multilib
        - sudo apt-get install -y linux-libc-dev:i386
      script: *script_linux
      env: &linux-32-toolchain
        - TOOLCHAIN="x86-toolchain.cmake"

      # Windows 64-bit
    - stage: build and test
      name: Windows 64-bit
      os: windows
      install: &install_windows
        - choco upgrade cmake
      env: &windows-64-toolchain
        - ARCH=" Win64"
      script: &script_windows
        - mkdir build && cd build
        - cmake -G "Visual Studio 15 2017${ARCH}" ..
        - cmake --build .
        - ctest --verbose

      # Windows 32-bit
    - stage: build and test
      name: Windows 32-bit
      os: windows
      install: *install_windows
      env: &windows-32-toolchain
        - ARCH=""
      script: *script_windows

      # Windows Deploy
    - stage: deploy binaries
      if: tag IS present
      name: Windows 32/64 Deploy
      os: windows
      install: *install_windows
      <<: *template_deploy

      # Linux Deploy
    - stage: deploy binaries
      if: tag IS present
      name: Linux 32/64 Deploy
      os: linux
      install: *install_linux
      before_script: *before-script-linux32
      <<: *template_deploy
